- id: '1610912946292'
  alias: Azan - 01 - Subuh
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.jakim_subuh") == states("sensor.time")}}'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.living_room_speaker
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Sekarang masuknya waktu subuh bagi Bandar Baru Bangi dan kawasan kawasan
        yang sewaktu dengannya
      language: id
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - service: media_extractor.play_media
    data:
      entity_id: media_player.living_room_speaker
      media_content_id: http://192.168.50.23:8123/local/audio/azansubuh.mp3
      media_content_type: music
  - service: media_extractor.play_media
    data:
      entity_id: media_player.mpd
      media_content_id: http://192.168.50.23:8123/local/audio/azansubuh.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - service: media_player.media_pause
    target:
      entity_id: media_player.living_room_speaker
  - service: media_player.media_play
    target:
      entity_id: media_player.living_room_speaker
  mode: single
- id: '1610915963986'
  alias: Azan - 02 - Zohor
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.jakim_zohor") == states("sensor.time")}}'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.living_room_speaker
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Sekarang masuknya waktu zohor bagi Bandar Baru Bangi dan kawasan kawasan
        yang sewaktu dengannya
      language: id
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - service: media_extractor.play_media
    data:
      entity_id: media_player.living_room_speaker
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - service: media_extractor.play_media
    data:
      entity_id: media_player.mpd
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - service: media_player.media_pause
    target:
      entity_id: media_player.living_room_speaker
  - service: media_player.media_play
    target:
      entity_id: media_player.living_room_speaker
  mode: single
- id: '1610916009800'
  alias: Azan - 03 -  Asar
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.jakim_asar") == states("sensor.time")}}'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.living_room_speaker
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Sekarang masuknya waktu asar bagi Bandar Baru Bangi dan kawasan kawasan
        yang sewaktu dengannya
      language: id
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - service: media_extractor.play_media
    data:
      entity_id: media_player.mpd
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - service: media_extractor.play_media
    data:
      entity_id: media_player.living_room_speaker
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - service: media_player.media_pause
    target:
      entity_id: media_player.living_room_speaker
  - service: media_player.media_play
    target:
      entity_id: media_player.living_room_speaker
  mode: single
- id: '1610916034660'
  alias: Azan - 04 - Maghrib
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.jakim_maghrib") == states("sensor.time")}}'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.living_room_speaker
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Sekarang masuknya waktu maghrib bagi Bandar Baru Bangi dan kawasan
        kawasan yang sewaktu dengannya
      language: id
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - service: media_extractor.play_media
    data:
      entity_id: media_player.living_room_speaker
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - service: media_extractor.play_media
    data:
      entity_id: media_player.mpd
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - service: media_player.media_pause
    target:
      entity_id: media_player.living_room_speaker
  - service: media_player.media_play
    target:
      entity_id: media_player.living_room_speaker
  mode: single
- id: '1610916052986'
  alias: Azan - 05 - Isyak
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.jakim_isyak") == states("sensor.time")}}'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.living_room_speaker
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Sekarang masuknya waktu isyak bagi Bandar Baru Bangi dan kawasan kawasan
        yang sewaktu dengannya
      language: id
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - service: media_extractor.play_media
    data:
      entity_id: media_player.living_room_speaker
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - service: media_extractor.play_media
    data:
      entity_id: media_player.mpd
      media_content_id: http://192.168.50.23:8123/local/audio/azan.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - service: media_player.media_pause
    target:
      entity_id: media_player.living_room_speaker
  - service: media_player.media_play
    target:
      entity_id: media_player.living_room_speaker
  mode: single
- id: '1611216388029'
  alias: Azan - 01 - Subuh - Imsak
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.jakim_imsak") == states("sensor.time")}}'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id: media_player.living_room_speaker
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Sekarang masuknya waktu imsak bagi Bandar Baru Bangi dan kawasan-kawasan
        sewaktu dengannya
      language: id
  mode: single
- id: '1610916523303'
  alias: Restart HA everyday at 03:00:00
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: homeassistant.restart
    data: {}
  mode: single
